/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vng.zing.emp.thrift.dto;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ProfileEmp implements org.apache.thrift.TBase<ProfileEmp, ProfileEmp._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ProfileEmp");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField EMP_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("emp_code", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField EMP_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("emp_name", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField ACTUAL_WORKING_DAY_FIELD_DESC = new org.apache.thrift.protocol.TField("actualWorkingDay", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField ACTUAL_WORKING_DAY_HOUR_FIELD_DESC = new org.apache.thrift.protocol.TField("actualWorkingDayHour", org.apache.thrift.protocol.TType.DOUBLE, (short)5);
  private static final org.apache.thrift.protocol.TField ACTUAL_HOUR_OFF_FIELD_DESC = new org.apache.thrift.protocol.TField("actualHourOff", org.apache.thrift.protocol.TType.DOUBLE, (short)6);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ProfileEmpStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ProfileEmpTupleSchemeFactory());
  }

  public int id; // required
  public String emp_code; // required
  public String emp_name; // required
  public int actualWorkingDay; // required
  public double actualWorkingDayHour; // required
  public double actualHourOff; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    EMP_CODE((short)2, "emp_code"),
    EMP_NAME((short)3, "emp_name"),
    ACTUAL_WORKING_DAY((short)4, "actualWorkingDay"),
    ACTUAL_WORKING_DAY_HOUR((short)5, "actualWorkingDayHour"),
    ACTUAL_HOUR_OFF((short)6, "actualHourOff");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // EMP_CODE
          return EMP_CODE;
        case 3: // EMP_NAME
          return EMP_NAME;
        case 4: // ACTUAL_WORKING_DAY
          return ACTUAL_WORKING_DAY;
        case 5: // ACTUAL_WORKING_DAY_HOUR
          return ACTUAL_WORKING_DAY_HOUR;
        case 6: // ACTUAL_HOUR_OFF
          return ACTUAL_HOUR_OFF;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __ACTUALWORKINGDAY_ISSET_ID = 1;
  private static final int __ACTUALWORKINGDAYHOUR_ISSET_ID = 2;
  private static final int __ACTUALHOUROFF_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.EMP_CODE, new org.apache.thrift.meta_data.FieldMetaData("emp_code", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.EMP_NAME, new org.apache.thrift.meta_data.FieldMetaData("emp_name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ACTUAL_WORKING_DAY, new org.apache.thrift.meta_data.FieldMetaData("actualWorkingDay", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.ACTUAL_WORKING_DAY_HOUR, new org.apache.thrift.meta_data.FieldMetaData("actualWorkingDayHour", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.ACTUAL_HOUR_OFF, new org.apache.thrift.meta_data.FieldMetaData("actualHourOff", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ProfileEmp.class, metaDataMap);
  }

  public ProfileEmp() {
  }

  public ProfileEmp(
    int id,
    String emp_code,
    String emp_name,
    int actualWorkingDay,
    double actualWorkingDayHour,
    double actualHourOff)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.emp_code = emp_code;
    this.emp_name = emp_name;
    this.actualWorkingDay = actualWorkingDay;
    setActualWorkingDayIsSet(true);
    this.actualWorkingDayHour = actualWorkingDayHour;
    setActualWorkingDayHourIsSet(true);
    this.actualHourOff = actualHourOff;
    setActualHourOffIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ProfileEmp(ProfileEmp other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    if (other.isSetEmp_code()) {
      this.emp_code = other.emp_code;
    }
    if (other.isSetEmp_name()) {
      this.emp_name = other.emp_name;
    }
    this.actualWorkingDay = other.actualWorkingDay;
    this.actualWorkingDayHour = other.actualWorkingDayHour;
    this.actualHourOff = other.actualHourOff;
  }

  public ProfileEmp deepCopy() {
    return new ProfileEmp(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    this.emp_code = null;
    this.emp_name = null;
    setActualWorkingDayIsSet(false);
    this.actualWorkingDay = 0;
    setActualWorkingDayHourIsSet(false);
    this.actualWorkingDayHour = 0.0;
    setActualHourOffIsSet(false);
    this.actualHourOff = 0.0;
  }

  public int getId() {
    return this.id;
  }

  public ProfileEmp setId(int id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public String getEmp_code() {
    return this.emp_code;
  }

  public ProfileEmp setEmp_code(String emp_code) {
    this.emp_code = emp_code;
    return this;
  }

  public void unsetEmp_code() {
    this.emp_code = null;
  }

  /** Returns true if field emp_code is set (has been assigned a value) and false otherwise */
  public boolean isSetEmp_code() {
    return this.emp_code != null;
  }

  public void setEmp_codeIsSet(boolean value) {
    if (!value) {
      this.emp_code = null;
    }
  }

  public String getEmp_name() {
    return this.emp_name;
  }

  public ProfileEmp setEmp_name(String emp_name) {
    this.emp_name = emp_name;
    return this;
  }

  public void unsetEmp_name() {
    this.emp_name = null;
  }

  /** Returns true if field emp_name is set (has been assigned a value) and false otherwise */
  public boolean isSetEmp_name() {
    return this.emp_name != null;
  }

  public void setEmp_nameIsSet(boolean value) {
    if (!value) {
      this.emp_name = null;
    }
  }

  public int getActualWorkingDay() {
    return this.actualWorkingDay;
  }

  public ProfileEmp setActualWorkingDay(int actualWorkingDay) {
    this.actualWorkingDay = actualWorkingDay;
    setActualWorkingDayIsSet(true);
    return this;
  }

  public void unsetActualWorkingDay() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ACTUALWORKINGDAY_ISSET_ID);
  }

  /** Returns true if field actualWorkingDay is set (has been assigned a value) and false otherwise */
  public boolean isSetActualWorkingDay() {
    return EncodingUtils.testBit(__isset_bitfield, __ACTUALWORKINGDAY_ISSET_ID);
  }

  public void setActualWorkingDayIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ACTUALWORKINGDAY_ISSET_ID, value);
  }

  public double getActualWorkingDayHour() {
    return this.actualWorkingDayHour;
  }

  public ProfileEmp setActualWorkingDayHour(double actualWorkingDayHour) {
    this.actualWorkingDayHour = actualWorkingDayHour;
    setActualWorkingDayHourIsSet(true);
    return this;
  }

  public void unsetActualWorkingDayHour() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ACTUALWORKINGDAYHOUR_ISSET_ID);
  }

  /** Returns true if field actualWorkingDayHour is set (has been assigned a value) and false otherwise */
  public boolean isSetActualWorkingDayHour() {
    return EncodingUtils.testBit(__isset_bitfield, __ACTUALWORKINGDAYHOUR_ISSET_ID);
  }

  public void setActualWorkingDayHourIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ACTUALWORKINGDAYHOUR_ISSET_ID, value);
  }

  public double getActualHourOff() {
    return this.actualHourOff;
  }

  public ProfileEmp setActualHourOff(double actualHourOff) {
    this.actualHourOff = actualHourOff;
    setActualHourOffIsSet(true);
    return this;
  }

  public void unsetActualHourOff() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ACTUALHOUROFF_ISSET_ID);
  }

  /** Returns true if field actualHourOff is set (has been assigned a value) and false otherwise */
  public boolean isSetActualHourOff() {
    return EncodingUtils.testBit(__isset_bitfield, __ACTUALHOUROFF_ISSET_ID);
  }

  public void setActualHourOffIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ACTUALHOUROFF_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((Integer)value);
      }
      break;

    case EMP_CODE:
      if (value == null) {
        unsetEmp_code();
      } else {
        setEmp_code((String)value);
      }
      break;

    case EMP_NAME:
      if (value == null) {
        unsetEmp_name();
      } else {
        setEmp_name((String)value);
      }
      break;

    case ACTUAL_WORKING_DAY:
      if (value == null) {
        unsetActualWorkingDay();
      } else {
        setActualWorkingDay((Integer)value);
      }
      break;

    case ACTUAL_WORKING_DAY_HOUR:
      if (value == null) {
        unsetActualWorkingDayHour();
      } else {
        setActualWorkingDayHour((Double)value);
      }
      break;

    case ACTUAL_HOUR_OFF:
      if (value == null) {
        unsetActualHourOff();
      } else {
        setActualHourOff((Double)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return Integer.valueOf(getId());

    case EMP_CODE:
      return getEmp_code();

    case EMP_NAME:
      return getEmp_name();

    case ACTUAL_WORKING_DAY:
      return Integer.valueOf(getActualWorkingDay());

    case ACTUAL_WORKING_DAY_HOUR:
      return Double.valueOf(getActualWorkingDayHour());

    case ACTUAL_HOUR_OFF:
      return Double.valueOf(getActualHourOff());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case EMP_CODE:
      return isSetEmp_code();
    case EMP_NAME:
      return isSetEmp_name();
    case ACTUAL_WORKING_DAY:
      return isSetActualWorkingDay();
    case ACTUAL_WORKING_DAY_HOUR:
      return isSetActualWorkingDayHour();
    case ACTUAL_HOUR_OFF:
      return isSetActualHourOff();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ProfileEmp)
      return this.equals((ProfileEmp)that);
    return false;
  }

  public boolean equals(ProfileEmp that) {
    if (that == null)
      return false;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_emp_code = true && this.isSetEmp_code();
    boolean that_present_emp_code = true && that.isSetEmp_code();
    if (this_present_emp_code || that_present_emp_code) {
      if (!(this_present_emp_code && that_present_emp_code))
        return false;
      if (!this.emp_code.equals(that.emp_code))
        return false;
    }

    boolean this_present_emp_name = true && this.isSetEmp_name();
    boolean that_present_emp_name = true && that.isSetEmp_name();
    if (this_present_emp_name || that_present_emp_name) {
      if (!(this_present_emp_name && that_present_emp_name))
        return false;
      if (!this.emp_name.equals(that.emp_name))
        return false;
    }

    boolean this_present_actualWorkingDay = true;
    boolean that_present_actualWorkingDay = true;
    if (this_present_actualWorkingDay || that_present_actualWorkingDay) {
      if (!(this_present_actualWorkingDay && that_present_actualWorkingDay))
        return false;
      if (this.actualWorkingDay != that.actualWorkingDay)
        return false;
    }

    boolean this_present_actualWorkingDayHour = true;
    boolean that_present_actualWorkingDayHour = true;
    if (this_present_actualWorkingDayHour || that_present_actualWorkingDayHour) {
      if (!(this_present_actualWorkingDayHour && that_present_actualWorkingDayHour))
        return false;
      if (this.actualWorkingDayHour != that.actualWorkingDayHour)
        return false;
    }

    boolean this_present_actualHourOff = true;
    boolean that_present_actualHourOff = true;
    if (this_present_actualHourOff || that_present_actualHourOff) {
      if (!(this_present_actualHourOff && that_present_actualHourOff))
        return false;
      if (this.actualHourOff != that.actualHourOff)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(ProfileEmp other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    ProfileEmp typedOther = (ProfileEmp)other;

    lastComparison = Boolean.valueOf(isSetId()).compareTo(typedOther.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, typedOther.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEmp_code()).compareTo(typedOther.isSetEmp_code());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEmp_code()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.emp_code, typedOther.emp_code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEmp_name()).compareTo(typedOther.isSetEmp_name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEmp_name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.emp_name, typedOther.emp_name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetActualWorkingDay()).compareTo(typedOther.isSetActualWorkingDay());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetActualWorkingDay()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.actualWorkingDay, typedOther.actualWorkingDay);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetActualWorkingDayHour()).compareTo(typedOther.isSetActualWorkingDayHour());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetActualWorkingDayHour()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.actualWorkingDayHour, typedOther.actualWorkingDayHour);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetActualHourOff()).compareTo(typedOther.isSetActualHourOff());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetActualHourOff()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.actualHourOff, typedOther.actualHourOff);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ProfileEmp(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("emp_code:");
    if (this.emp_code == null) {
      sb.append("null");
    } else {
      sb.append(this.emp_code);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("emp_name:");
    if (this.emp_name == null) {
      sb.append("null");
    } else {
      sb.append(this.emp_name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("actualWorkingDay:");
    sb.append(this.actualWorkingDay);
    first = false;
    if (!first) sb.append(", ");
    sb.append("actualWorkingDayHour:");
    sb.append(this.actualWorkingDayHour);
    first = false;
    if (!first) sb.append(", ");
    sb.append("actualHourOff:");
    sb.append(this.actualHourOff);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'id' because it's a primitive and you chose the non-beans generator.
    if (emp_code == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'emp_code' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ProfileEmpStandardSchemeFactory implements SchemeFactory {
    public ProfileEmpStandardScheme getScheme() {
      return new ProfileEmpStandardScheme();
    }
  }

  private static class ProfileEmpStandardScheme extends StandardScheme<ProfileEmp> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ProfileEmp struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.id = iprot.readI32();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // EMP_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.emp_code = iprot.readString();
              struct.setEmp_codeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // EMP_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.emp_name = iprot.readString();
              struct.setEmp_nameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // ACTUAL_WORKING_DAY
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.actualWorkingDay = iprot.readI32();
              struct.setActualWorkingDayIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // ACTUAL_WORKING_DAY_HOUR
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.actualWorkingDayHour = iprot.readDouble();
              struct.setActualWorkingDayHourIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // ACTUAL_HOUR_OFF
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.actualHourOff = iprot.readDouble();
              struct.setActualHourOffIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'id' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ProfileEmp struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI32(struct.id);
      oprot.writeFieldEnd();
      if (struct.emp_code != null) {
        oprot.writeFieldBegin(EMP_CODE_FIELD_DESC);
        oprot.writeString(struct.emp_code);
        oprot.writeFieldEnd();
      }
      if (struct.emp_name != null) {
        oprot.writeFieldBegin(EMP_NAME_FIELD_DESC);
        oprot.writeString(struct.emp_name);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(ACTUAL_WORKING_DAY_FIELD_DESC);
      oprot.writeI32(struct.actualWorkingDay);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ACTUAL_WORKING_DAY_HOUR_FIELD_DESC);
      oprot.writeDouble(struct.actualWorkingDayHour);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ACTUAL_HOUR_OFF_FIELD_DESC);
      oprot.writeDouble(struct.actualHourOff);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ProfileEmpTupleSchemeFactory implements SchemeFactory {
    public ProfileEmpTupleScheme getScheme() {
      return new ProfileEmpTupleScheme();
    }
  }

  private static class ProfileEmpTupleScheme extends TupleScheme<ProfileEmp> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ProfileEmp struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.id);
      oprot.writeString(struct.emp_code);
      BitSet optionals = new BitSet();
      if (struct.isSetEmp_name()) {
        optionals.set(0);
      }
      if (struct.isSetActualWorkingDay()) {
        optionals.set(1);
      }
      if (struct.isSetActualWorkingDayHour()) {
        optionals.set(2);
      }
      if (struct.isSetActualHourOff()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetEmp_name()) {
        oprot.writeString(struct.emp_name);
      }
      if (struct.isSetActualWorkingDay()) {
        oprot.writeI32(struct.actualWorkingDay);
      }
      if (struct.isSetActualWorkingDayHour()) {
        oprot.writeDouble(struct.actualWorkingDayHour);
      }
      if (struct.isSetActualHourOff()) {
        oprot.writeDouble(struct.actualHourOff);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ProfileEmp struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.id = iprot.readI32();
      struct.setIdIsSet(true);
      struct.emp_code = iprot.readString();
      struct.setEmp_codeIsSet(true);
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.emp_name = iprot.readString();
        struct.setEmp_nameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.actualWorkingDay = iprot.readI32();
        struct.setActualWorkingDayIsSet(true);
      }
      if (incoming.get(2)) {
        struct.actualWorkingDayHour = iprot.readDouble();
        struct.setActualWorkingDayHourIsSet(true);
      }
      if (incoming.get(3)) {
        struct.actualHourOff = iprot.readDouble();
        struct.setActualHourOffIsSet(true);
      }
    }
  }

}

