/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vng.zing.emp.thrift.dto;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Title implements org.apache.thrift.TBase<Title, Title._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Title");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField TITLE_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("title_code", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField TITLE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("title_name", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TitleStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TitleTupleSchemeFactory());
  }

  public int id; // required
  public String title_code; // required
  public String title_name; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    TITLE_CODE((short)2, "title_code"),
    TITLE_NAME((short)3, "title_name");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // TITLE_CODE
          return TITLE_CODE;
        case 3: // TITLE_NAME
          return TITLE_NAME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TITLE_CODE, new org.apache.thrift.meta_data.FieldMetaData("title_code", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TITLE_NAME, new org.apache.thrift.meta_data.FieldMetaData("title_name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Title.class, metaDataMap);
  }

  public Title() {
  }

  public Title(
    int id,
    String title_code,
    String title_name)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.title_code = title_code;
    this.title_name = title_name;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Title(Title other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    if (other.isSetTitle_code()) {
      this.title_code = other.title_code;
    }
    if (other.isSetTitle_name()) {
      this.title_name = other.title_name;
    }
  }

  public Title deepCopy() {
    return new Title(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    this.title_code = null;
    this.title_name = null;
  }

  public int getId() {
    return this.id;
  }

  public Title setId(int id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public String getTitle_code() {
    return this.title_code;
  }

  public Title setTitle_code(String title_code) {
    this.title_code = title_code;
    return this;
  }

  public void unsetTitle_code() {
    this.title_code = null;
  }

  /** Returns true if field title_code is set (has been assigned a value) and false otherwise */
  public boolean isSetTitle_code() {
    return this.title_code != null;
  }

  public void setTitle_codeIsSet(boolean value) {
    if (!value) {
      this.title_code = null;
    }
  }

  public String getTitle_name() {
    return this.title_name;
  }

  public Title setTitle_name(String title_name) {
    this.title_name = title_name;
    return this;
  }

  public void unsetTitle_name() {
    this.title_name = null;
  }

  /** Returns true if field title_name is set (has been assigned a value) and false otherwise */
  public boolean isSetTitle_name() {
    return this.title_name != null;
  }

  public void setTitle_nameIsSet(boolean value) {
    if (!value) {
      this.title_name = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((Integer)value);
      }
      break;

    case TITLE_CODE:
      if (value == null) {
        unsetTitle_code();
      } else {
        setTitle_code((String)value);
      }
      break;

    case TITLE_NAME:
      if (value == null) {
        unsetTitle_name();
      } else {
        setTitle_name((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return Integer.valueOf(getId());

    case TITLE_CODE:
      return getTitle_code();

    case TITLE_NAME:
      return getTitle_name();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case TITLE_CODE:
      return isSetTitle_code();
    case TITLE_NAME:
      return isSetTitle_name();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Title)
      return this.equals((Title)that);
    return false;
  }

  public boolean equals(Title that) {
    if (that == null)
      return false;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_title_code = true && this.isSetTitle_code();
    boolean that_present_title_code = true && that.isSetTitle_code();
    if (this_present_title_code || that_present_title_code) {
      if (!(this_present_title_code && that_present_title_code))
        return false;
      if (!this.title_code.equals(that.title_code))
        return false;
    }

    boolean this_present_title_name = true && this.isSetTitle_name();
    boolean that_present_title_name = true && that.isSetTitle_name();
    if (this_present_title_name || that_present_title_name) {
      if (!(this_present_title_name && that_present_title_name))
        return false;
      if (!this.title_name.equals(that.title_name))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(Title other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    Title typedOther = (Title)other;

    lastComparison = Boolean.valueOf(isSetId()).compareTo(typedOther.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, typedOther.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTitle_code()).compareTo(typedOther.isSetTitle_code());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTitle_code()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.title_code, typedOther.title_code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTitle_name()).compareTo(typedOther.isSetTitle_name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTitle_name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.title_name, typedOther.title_name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Title(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("title_code:");
    if (this.title_code == null) {
      sb.append("null");
    } else {
      sb.append(this.title_code);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("title_name:");
    if (this.title_name == null) {
      sb.append("null");
    } else {
      sb.append(this.title_name);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'id' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TitleStandardSchemeFactory implements SchemeFactory {
    public TitleStandardScheme getScheme() {
      return new TitleStandardScheme();
    }
  }

  private static class TitleStandardScheme extends StandardScheme<Title> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Title struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.id = iprot.readI32();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TITLE_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.title_code = iprot.readString();
              struct.setTitle_codeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TITLE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.title_name = iprot.readString();
              struct.setTitle_nameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'id' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Title struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI32(struct.id);
      oprot.writeFieldEnd();
      if (struct.title_code != null) {
        oprot.writeFieldBegin(TITLE_CODE_FIELD_DESC);
        oprot.writeString(struct.title_code);
        oprot.writeFieldEnd();
      }
      if (struct.title_name != null) {
        oprot.writeFieldBegin(TITLE_NAME_FIELD_DESC);
        oprot.writeString(struct.title_name);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TitleTupleSchemeFactory implements SchemeFactory {
    public TitleTupleScheme getScheme() {
      return new TitleTupleScheme();
    }
  }

  private static class TitleTupleScheme extends TupleScheme<Title> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Title struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.id);
      BitSet optionals = new BitSet();
      if (struct.isSetTitle_code()) {
        optionals.set(0);
      }
      if (struct.isSetTitle_name()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetTitle_code()) {
        oprot.writeString(struct.title_code);
      }
      if (struct.isSetTitle_name()) {
        oprot.writeString(struct.title_name);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Title struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.id = iprot.readI32();
      struct.setIdIsSet(true);
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.title_code = iprot.readString();
        struct.setTitle_codeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.title_name = iprot.readString();
        struct.setTitle_nameIsSet(true);
      }
    }
  }

}

